The purpose of this notebook is to combine data_sets in extracted_data 
for making it in a format that a machine learning algorithm can train on

In [2]:
import pandas as pd
import numpy as np

In [3]:
features_csv = pd.read_csv('extracted_data/features.csv')
train_csv = pd.read_csv('extracted_data/train.csv')

In [4]:
# Remove duplicate columns named below
del features_csv['Unnamed: 0']
del features_csv['IsHoliday']
del features_csv['Store']
features_csv.head()

,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment
0,2010-02-05,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
1,2010-02-12,39.81,2.548,NaN,NaN,NaN,NaN,NaN,211.800470,6.566
2,2010-02-19,41.14,2.514,NaN,NaN,NaN,NaN,NaN,211.847128,6.566
3,2010-02-26,46.70,2.561,NaN,NaN,NaN,NaN,NaN,211.877147,6.566
4,2010-03-05,48.89,2.625,NaN,NaN,NaN,NaN,NaN,211.907165,6.566

In [5]:
# Remove an unnamed index
del train_csv['Unnamed: 0']
train_csv.head()

   Store  Dept        Date  Weekly_Sales  IsHoliday
0      5     1  2010-02-05       9323.89      False
1      5     1  2010-02-12      16861.10       True
2      5     1  2010-02-19      11417.67      False
3      5     1  2010-02-26       7168.41      False
4      5     1  2010-03-05       8344.13      False

In [6]:
# Merge two dataframes together
merged_data_set = pd.merge(train_csv, features_csv, on="Date", validate="many_to_one")
merged_data_set

,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment
0,5,1,2010-02-05,9323.89,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
1,5,2,2010-02-05,11955.45,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
2,5,3,2010-02-05,4190.20,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
3,5,4,2010-02-05,9282.86,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
4,5,5,2010-02-05,10934.88,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
5,5,6,2010-02-05,1373.45,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
6,5,7,2010-02-05,4401.08,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
7,5,8,2010-02-05,14337.76,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
8,5,9,2010-02-05,4877.38,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
9,5,10,2010-02-05,8372.87,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
10,5,11,2010-02-05,5501.87,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
11,5,12,2010-02-05,2138.59,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
12,5,13,2010-02-05,11468.24,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
13,5,14,2010-02-05,3327.63,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
14,5,16,2010-02-05,4545.64,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
15,5,17,2010-02-05,2425.47,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
16,5,18,2010-02-05,1444.00,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
17,5,19,2010-02-05,63.95,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
18,5,20,2010-02-05,1308.84,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
19,5,21,2010-02-05,2002.48,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
20,5,22,2010-02-05,2628.64,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
21,5,23,2010-02-05,7253.83,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
22,5,24,2010-02-05,1520.00,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
23,5,25,2010-02-05,2516.00,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
24,5,26,2010-02-05,2054.31,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
25,5,27,2010-02-05,435.50,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
26,5,28,2010-02-05,313.40,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
27,5,29,2010-02-05,1734.49,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
28,5,30,2010-02-05,1176.26,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
29,5,31,2010-02-05,605.00,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8594,5,36,2012-09-14,125.74,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8595,5,38,2012-09-14,58289.95,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8596,5,40,2012-09-14,19691.65,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8597,5,41,2012-09-14,1428.89,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8598,5,42,2012-09-14,2824.43,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8599,5,44,2012-09-14,1204.68,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8600,5,46,2012-09-14,4385.83,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8601,5,49,2012-09-14,28.00,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8602,5,52,2012-09-14,294.57,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8603,5,54,2012-09-14,5.88,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8604,5,55,2012-09-14,2279.32,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8605,5,56,2012-09-14,248.46,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8606,5,58,2012-09-14,265.00,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8607,5,60,2012-09-14,252.00,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8608,5,67,2012-09-14,2509.88,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8609,5,71,2012-09-14,195.04,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8610,5,72,2012-09-14,11038.42,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8611,5,74,2012-09-14,2672.76,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8612,5,79,2012-09-14,4766.50,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8613,5,81,2012-09-14,3007.34,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8614,5,82,2012-09-14,3782.64,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8615,5,85,2012-09-14,405.39,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8616,5,87,2012-09-14,10498.97,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8617,5,90,2012-09-14,3129.62,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8618,5,91,2012-09-14,1584.63,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8619,5,92,2012-09-14,8388.58,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8620,5,94,2012-09-14,15.52,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8621,5,95,2012-09-14,20017.76,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8622,5,96,2012-09-14,7491.26,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8623,5,97,2012-09-14,684.71,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603

In [7]:
#The below function was used to check that the keys on 
#the right managed to match against the left
#pd.merge(train_csv, features_csv, on="Date", validate="one_to_many")

In [8]:
# Drop the store element since it's not needed for the curreint implementation
del merged_data_set['Store']
merged_data_set

,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment
0,1,2010-02-05,9323.89,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
1,2,2010-02-05,11955.45,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
2,3,2010-02-05,4190.20,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
3,4,2010-02-05,9282.86,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
4,5,2010-02-05,10934.88,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
5,6,2010-02-05,1373.45,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
6,7,2010-02-05,4401.08,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
7,8,2010-02-05,14337.76,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
8,9,2010-02-05,4877.38,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
9,10,2010-02-05,8372.87,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
10,11,2010-02-05,5501.87,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
11,12,2010-02-05,2138.59,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
12,13,2010-02-05,11468.24,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
13,14,2010-02-05,3327.63,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
14,16,2010-02-05,4545.64,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
15,17,2010-02-05,2425.47,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
16,18,2010-02-05,1444.00,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
17,19,2010-02-05,63.95,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
18,20,2010-02-05,1308.84,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
19,21,2010-02-05,2002.48,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
20,22,2010-02-05,2628.64,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
21,23,2010-02-05,7253.83,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
22,24,2010-02-05,1520.00,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
23,25,2010-02-05,2516.00,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
24,26,2010-02-05,2054.31,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
25,27,2010-02-05,435.50,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
26,28,2010-02-05,313.40,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
27,29,2010-02-05,1734.49,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
28,30,2010-02-05,1176.26,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
29,31,2010-02-05,605.00,False,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8594,36,2012-09-14,125.74,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8595,38,2012-09-14,58289.95,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8596,40,2012-09-14,19691.65,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8597,41,2012-09-14,1428.89,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8598,42,2012-09-14,2824.43,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8599,44,2012-09-14,1204.68,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8600,46,2012-09-14,4385.83,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8601,49,2012-09-14,28.00,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8602,52,2012-09-14,294.57,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8603,54,2012-09-14,5.88,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8604,55,2012-09-14,2279.32,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8605,56,2012-09-14,248.46,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8606,58,2012-09-14,265.00,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8607,60,2012-09-14,252.00,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8608,67,2012-09-14,2509.88,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8609,71,2012-09-14,195.04,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8610,72,2012-09-14,11038.42,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8611,74,2012-09-14,2672.76,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8612,79,2012-09-14,4766.50,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8613,81,2012-09-14,3007.34,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8614,82,2012-09-14,3782.64,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8615,85,2012-09-14,405.39,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8616,87,2012-09-14,10498.97,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8617,90,2012-09-14,3129.62,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8618,91,2012-09-14,1584.63,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8619,92,2012-09-14,8388.58,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8620,94,2012-09-14,15.52,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8621,95,2012-09-14,20017.76,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8622,96,2012-09-14,7491.26,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8623,97,2012-09-14,684.71,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603

In [9]:
# Insert 0 for null values in the markdown
merged_data_set = merged_data_set.fillna(value=0); merged_data_set

,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment
0,1,2010-02-05,9323.89,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
1,2,2010-02-05,11955.45,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
2,3,2010-02-05,4190.20,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
3,4,2010-02-05,9282.86,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
4,5,2010-02-05,10934.88,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
5,6,2010-02-05,1373.45,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
6,7,2010-02-05,4401.08,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
7,8,2010-02-05,14337.76,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
8,9,2010-02-05,4877.38,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
9,10,2010-02-05,8372.87,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
10,11,2010-02-05,5501.87,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
11,12,2010-02-05,2138.59,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
12,13,2010-02-05,11468.24,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
13,14,2010-02-05,3327.63,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
14,16,2010-02-05,4545.64,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
15,17,2010-02-05,2425.47,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
16,18,2010-02-05,1444.00,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
17,19,2010-02-05,63.95,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
18,20,2010-02-05,1308.84,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
19,21,2010-02-05,2002.48,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
20,22,2010-02-05,2628.64,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
21,23,2010-02-05,7253.83,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
22,24,2010-02-05,1520.00,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
23,25,2010-02-05,2516.00,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
24,26,2010-02-05,2054.31,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
25,27,2010-02-05,435.50,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
26,28,2010-02-05,313.40,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
27,29,2010-02-05,1734.49,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
28,30,2010-02-05,1176.26,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
29,31,2010-02-05,605.00,False,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8594,36,2012-09-14,125.74,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8595,38,2012-09-14,58289.95,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8596,40,2012-09-14,19691.65,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8597,41,2012-09-14,1428.89,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8598,42,2012-09-14,2824.43,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8599,44,2012-09-14,1204.68,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8600,46,2012-09-14,4385.83,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8601,49,2012-09-14,28.00,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8602,52,2012-09-14,294.57,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8603,54,2012-09-14,5.88,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8604,55,2012-09-14,2279.32,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8605,56,2012-09-14,248.46,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8606,58,2012-09-14,265.00,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8607,60,2012-09-14,252.00,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8608,67,2012-09-14,2509.88,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8609,71,2012-09-14,195.04,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8610,72,2012-09-14,11038.42,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8611,74,2012-09-14,2672.76,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8612,79,2012-09-14,4766.50,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8613,81,2012-09-14,3007.34,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8614,82,2012-09-14,3782.64,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8615,85,2012-09-14,405.39,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8616,87,2012-09-14,10498.97,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8617,90,2012-09-14,3129.62,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8618,91,2012-09-14,1584.63,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8619,92,2012-09-14,8388.58,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8620,94,2012-09-14,15.52,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8621,95,2012-09-14,20017.76,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8622,96,2012-09-14,7491.26,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
8623,97,2012-09-14,684.71,False,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603

Upon inspection noticed that there are some rows that have a negative value for weekly sales.
Update, apparently to this [post](https://www.kaggle.com/c/walmart-recruiting-store-sales-forecasting/discussion/7152)
the reason there are negative sales is because people returned a lot more items than a store could make 
sales to make profit

In [10]:
merged_data_set.describe()

,Dept,Weekly_Sales,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment
count,8624.000000,8624.000000,8624.000000,8624.000000,8624.000000,8624.000000,8624.000000,8624.000000,8624.000000,8624.000000,8624.000000
mean,41.293019,5050.665334,69.114610,3.203662,1052.391012,313.160543,245.318428,396.287550,860.297633,216.262725,6.331954
std,29.071420,8057.279561,14.478548,0.425761,2550.537942,1668.422916,2575.198691,1443.608264,2349.305626,4.156152,0.352558
min,1.000000,-101.260000,37.740000,2.514000,0.000000,-10.980000,0.000000,0.000000,0.000000,210.887277,5.603000
25%,17.000000,923.007500,57.690000,2.735000,0.000000,0.000000,0.000000,0.000000,0.000000,212.076935,5.943000
50%,34.000000,2574.175000,70.580000,3.285000,0.000000,0.000000,0.000000,0.000000,0.000000,215.859267,6.489000
75%,60.000000,6370.172500,81.640000,3.561000,1197.530000,0.000000,1.000000,206.000000,1276.750000,220.569410,6.566000
max,98.000000,93517.720000,91.070000,3.907000,23811.410000,17079.760000,29333.060000,14928.420000,24751.930000,223.173417,6.768000

In [11]:
# Time to save the data to a file
merged_data_set.to_csv('clean_data/train.csv', index=False)