The purpose of this notebook is to combine data_sets in extracted_data 
for making it in a format that a machine learning algorithm can train on.


Different thing about this data set is that it uses weekly sales of the stores rather than the department's.

In [8]:
import pandas as pd
import numpy as np

In [9]:
features_csv = pd.read_csv('extracted_data/features.csv')
weekly_store_sales_csv = pd.read_csv('clean_data/weekly_store_sales.csv')

In [10]:
# Remove duplicate columns named below
del features_csv['Unnamed: 0']
del features_csv['IsHoliday']
del features_csv['Store']
features_csv.head()

,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment
0,2010-02-05,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
1,2010-02-12,39.81,2.548,NaN,NaN,NaN,NaN,NaN,211.800470,6.566
2,2010-02-19,41.14,2.514,NaN,NaN,NaN,NaN,NaN,211.847128,6.566
3,2010-02-26,46.70,2.561,NaN,NaN,NaN,NaN,NaN,211.877147,6.566
4,2010-03-05,48.89,2.625,NaN,NaN,NaN,NaN,NaN,211.907165,6.566

In [11]:
weekly_store_sales_csv.head()

   Store        Date  Weekly_Sales
0      1  2010-02-05    1643690.90
1      1  2010-02-12    1641957.44
2      1  2010-02-19    1611968.17
3      1  2010-02-26    1409727.59
4      1  2010-03-05    1554806.68

In [12]:
# Merge two dataframes together
merged_data_set = pd.merge(weekly_store_sales_csv, features_csv, on="Date", validate="many_to_one")
merged_data_set

,Store,Date,Weekly_Sales,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment
0,1,2010-02-05,1643690.90,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
1,2,2010-02-05,2136989.46,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
2,3,2010-02-05,461622.22,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
3,4,2010-02-05,2135143.87,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
4,5,2010-02-05,317173.10,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
5,6,2010-02-05,1652635.10,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
6,7,2010-02-05,496725.44,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
7,8,2010-02-05,1004137.09,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
8,9,2010-02-05,549505.55,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
9,10,2010-02-05,2193048.75,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
10,11,2010-02-05,1528008.64,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
11,12,2010-02-05,1100046.37,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
12,13,2010-02-05,1967220.53,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
13,14,2010-02-05,2623469.95,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
14,15,2010-02-05,652122.44,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
15,16,2010-02-05,477409.30,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
16,17,2010-02-05,789036.02,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
17,18,2010-02-05,1205307.50,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
18,19,2010-02-05,1507637.17,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
19,20,2010-02-05,2401395.47,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
20,21,2010-02-05,798593.88,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
21,22,2010-02-05,1033017.37,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
22,23,2010-02-05,1364721.58,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
23,24,2010-02-05,1388725.63,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
24,25,2010-02-05,677231.63,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
25,26,2010-02-05,1034119.21,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
26,27,2010-02-05,1874289.79,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
27,28,2010-02-05,1672352.29,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
28,29,2010-02-05,538634.46,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
29,30,2010-02-05,465108.52,39.70,2.572,NaN,NaN,NaN,NaN,NaN,211.653972,6.566
...,...,...,...,...,...,...,...,...,...,...,...,...
6135,16,2012-09-14,526525.16,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6136,17,2012-09-14,1071040.22,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6137,18,2012-09-14,960476.10,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6138,19,2012-09-14,1370653.41,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6139,20,2012-09-14,2047949.98,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6140,21,2012-09-14,628494.63,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6141,22,2012-09-14,918049.28,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6142,23,2012-09-14,1279041.64,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6143,24,2012-09-14,1242909.53,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6144,25,2012-09-14,657241.63,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6145,26,2012-09-14,986131.94,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6146,27,2012-09-14,1519604.50,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6147,28,2012-09-14,1124660.77,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6148,29,2012-09-14,475127.18,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6149,30,2012-09-14,437773.31,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6150,31,2012-09-14,1327705.44,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6151,32,2012-09-14,1156377.47,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6152,33,2012-09-14,277417.53,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6153,34,2012-09-14,955211.70,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6154,35,2012-09-14,821568.64,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6155,36,2012-09-14,301893.63,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6156,37,2012-09-14,514651.74,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6157,38,2012-09-14,430944.39,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6158,39,2012-09-14,1447614.08,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6159,40,2012-09-14,901709.82,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6160,41,2012-09-14,1306644.25,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6161,42,2012-09-14,586737.66,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6162,43,2012-09-14,625196.94,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6163,44,2012-09-14,347726.67,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6164,45,2012-09-14,702238.27,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603

In [7]:
#The below function was used to check that the keys on 
#the right managed to match against the left
#pd.merge(train_csv, features_csv, on="Date", validate="one_to_many")

In [13]:
# Insert 0 for null values in the markdown
merged_data_set = merged_data_set.fillna(value=0); merged_data_set

,Store,Date,Weekly_Sales,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment
0,1,2010-02-05,1643690.90,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
1,2,2010-02-05,2136989.46,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
2,3,2010-02-05,461622.22,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
3,4,2010-02-05,2135143.87,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
4,5,2010-02-05,317173.10,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
5,6,2010-02-05,1652635.10,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
6,7,2010-02-05,496725.44,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
7,8,2010-02-05,1004137.09,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
8,9,2010-02-05,549505.55,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
9,10,2010-02-05,2193048.75,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
10,11,2010-02-05,1528008.64,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
11,12,2010-02-05,1100046.37,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
12,13,2010-02-05,1967220.53,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
13,14,2010-02-05,2623469.95,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
14,15,2010-02-05,652122.44,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
15,16,2010-02-05,477409.30,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
16,17,2010-02-05,789036.02,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
17,18,2010-02-05,1205307.50,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
18,19,2010-02-05,1507637.17,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
19,20,2010-02-05,2401395.47,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
20,21,2010-02-05,798593.88,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
21,22,2010-02-05,1033017.37,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
22,23,2010-02-05,1364721.58,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
23,24,2010-02-05,1388725.63,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
24,25,2010-02-05,677231.63,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
25,26,2010-02-05,1034119.21,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
26,27,2010-02-05,1874289.79,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
27,28,2010-02-05,1672352.29,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
28,29,2010-02-05,538634.46,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
29,30,2010-02-05,465108.52,39.70,2.572,0.00,0.0,0.00,0.00,0.00,211.653972,6.566
...,...,...,...,...,...,...,...,...,...,...,...,...
6135,16,2012-09-14,526525.16,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6136,17,2012-09-14,1071040.22,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6137,18,2012-09-14,960476.10,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6138,19,2012-09-14,1370653.41,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6139,20,2012-09-14,2047949.98,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6140,21,2012-09-14,628494.63,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6141,22,2012-09-14,918049.28,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6142,23,2012-09-14,1279041.64,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6143,24,2012-09-14,1242909.53,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6144,25,2012-09-14,657241.63,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6145,26,2012-09-14,986131.94,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6146,27,2012-09-14,1519604.50,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6147,28,2012-09-14,1124660.77,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6148,29,2012-09-14,475127.18,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6149,30,2012-09-14,437773.31,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6150,31,2012-09-14,1327705.44,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6151,32,2012-09-14,1156377.47,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6152,33,2012-09-14,277417.53,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6153,34,2012-09-14,955211.70,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6154,35,2012-09-14,821568.64,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6155,36,2012-09-14,301893.63,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6156,37,2012-09-14,514651.74,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6157,38,2012-09-14,430944.39,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6158,39,2012-09-14,1447614.08,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6159,40,2012-09-14,901709.82,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6160,41,2012-09-14,1306644.25,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6161,42,2012-09-14,586737.66,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6162,43,2012-09-14,625196.94,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6163,44,2012-09-14,347726.67,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603
6164,45,2012-09-14,702238.27,76.65,3.717,2027.18,4.0,4.55,1354.97,3535.01,223.173417,5.603

Upon inspection noticed that there are some rows that have a negative value for weekly sales.
Update, apparently to this [post](https://www.kaggle.com/c/walmart-recruiting-store-sales-forecasting/discussion/7152)
the reason there are negative sales is because people returned a lot more items than a store could make 
sales to make profit

In [14]:
merged_data_set.describe()

,Store,Weekly_Sales,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment
count,6165.000000,6.165000e+03,6165.000000,6165.000000,6165.000000,6165.000000,6165.000000,6165.000000,6165.000000,6165.000000,6165.000000
mean,23.000000,1.048624e+06,69.328102,3.202277,1048.681606,302.902847,231.160219,395.089197,854.063431,216.249080,6.331015
std,12.988227,5.662836e+05,14.458119,0.426455,2537.931260,1627.443290,2496.858951,1434.695334,2333.726632,4.166521,0.353622
min,1.000000,2.099863e+05,37.740000,2.514000,0.000000,-10.980000,0.000000,0.000000,0.000000,210.887277,5.603000
25%,12.000000,5.548797e+05,57.750000,2.735000,0.000000,0.000000,0.000000,0.000000,0.000000,212.076935,5.943000
50%,23.000000,9.611862e+05,70.710000,3.285000,0.000000,0.000000,0.000000,0.000000,0.000000,215.859267,6.489000
75%,34.000000,1.422712e+06,81.640000,3.561000,1197.530000,0.000000,0.700000,206.000000,1276.750000,220.569410,6.529000
max,45.000000,3.818686e+06,91.070000,3.907000,23811.410000,17079.760000,29333.060000,14928.420000,24751.930000,223.173417,6.768000

In [15]:
# Time to save the data to a file
merged_data_set.to_csv('clean_data/train.csv', index=False)